package ast

type AstVisitor interface {
	visitAst(Ast)
	visitFunctionDef(FunctionDef)
	visitPrintStatement(PrintStmt)
	visitAssignStatement(AssignStmt)
	visitAssert(AssertStmt)
	visitReturn(ReturnStmt)
	visitReturnWithExpr(ReturnWithExprStmt)
	visitIfStatement(IfStmt)
	visitWhileStatement(WhileStmt)
	visitBinaryExpression(BinaryExpr)
	visitUnaryExpression(UnaryExpr)
	visitInt(Int)
	visitBool(Bool)
	visitVar(Var)
	visitFunctionCall(FunctionCall)
	visitAddressOfFunction(AddressOfFunction)
	visitTernaryExpression(TernaryExpr)
	visitNewListExpression(NewListExpr)
	visitLenExpression(LenExpr)
	visitSubscriptGetExpression(SubscriptGet)
	visitAssignVarExpression(AssignVar)
	visitSubscriptSetExpression(SubscriptSet)
}
